"""
    SlateAssess

Multiple-choice assessments that survive being exported to a single HTML file.

The shape of the thing: an author writes the paper as an ordinary Slate notebook — question prose in
markdown, figures and tables generated by Julia — and drops an [`answer_box`](@ref) under each question.
Exporting the notebook to standalone HTML produces one file that runs the whole paper in the browser with
**no Julia, no server and no network**, which is what a locked-down exam browser needs.

Two properties are worth stating plainly, because they are what make this usable for real assessment:

1. **The correct answers are never in the delivered file.** Nothing is marked in the browser. Candidates
   produce a signed submission; marking happens afterwards on the examiner's machine, against an
   [`AnswerKey`](@ref) that never left it. There is nothing in the artifact to extract.

2. **A submission is signed** ([`sign_submission`](@ref)) so a file edited after the fact is detectable.
   The signing key is embedded in the paper — it must be, since there is no server to call — so this is
   tamper-evidence, not proof against a determined forger. See `src/hmac.jl` for the honest bounds.

# Authoring

```julia
using SlateAssess

exam = Assessment("macro-resit-2026";
    title = "Macroeconomics — Resit",
    questions = questions("q", 50),
    marks = Marks(correct = 0.4, wrong = -0.1),
    duration = 90,
    session_key = ENV["EXAM_KEY"])

exam_header(exam)          # first cell — carries the runtime, locks the paper until identity is confirmed
answer_box(exam, "q01")    # under each question's markdown
submission_panel(exam)     # last cell
```

Export with **Offline** ticked so the page carries its own copy of every library.

# Marking

```julia
key = AnswerKey("q01" => "c)", "q02" => "a)", ...)
results = grade("submissions/", exam, key)
write_csv("marks.csv", report(results, exam)...)
```

or run `julia scripts/grade.jl` for the command-line version.
"""
module SlateAssess

using SHA
using Dates
using Random
import JSON

export Assessment, IdField, Marks, AnswerKey, questions,
       exam_header, answer_box, status_strip, submission_panel, AssessWidget,
       Submission, Result, read_submission, verify, grade, report, item_analysis,
       sign_submission, hmac_sha256, canonical_message,
       answer_code, answer_label, ANSWER_NR, ANSWER_FLAG,
       sat_in_seb, config_key_matches,
       read_csv, write_csv, shuffled_key

include("types.jl")
include("hmac.jl")
include("csv.jl")
include("render.jl")
include("grade.jl")

"""
    shuffled_key(a::Assessment, key::AnswerKey, seed) -> (order, key′)

Deterministically permute the option order per question, returning the per-question permutation and the
answer key rewritten to match.

Use it to build variant papers from one source: the same `seed` always reproduces the same paper, so a
variant can be regenerated from its seed alone months later when a mark is queried.

`order[qid]` maps a POSITION in the presented paper to the original option, so an author rendering
question prose can reorder their option text with the same permutation.
"""
function shuffled_key(a::Assessment, key::AnswerKey, seed::Integer)
    order = Dict{String,Vector{String}}()
    newkey = Dict{String,String}()
    for (i, q) in enumerate(a.questions)
        rng = Random.MersenneTwister(hash((seed, q)) % typemax(Int32))
        perm = Random.shuffle(rng, a.choices)
        order[q] = perm
        if haskey(key, q)
            # The key names an option LABEL ("c)"); after permuting, the correct answer sits at whatever
            # label now holds the originally-correct content.
            idx = findfirst(==(key[q]), a.choices)
            idx === nothing && throw(ArgumentError(
                "answer key for $q is \"$(key[q])\", which is not one of the assessment's choices"))
            pos = findfirst(==(a.choices[idx]), perm)
            newkey[q] = a.choices[pos]
        end
    end
    return (order, AnswerKey(newkey))
end

end # module
